[database]
# database type (bolt, gorm)
type = "bolt"
# database path
path = "npm.db"
# example usage for gorm (http://jinzhu.me/gorm/database.html#connecting-to-a-database):
# path = ["mysql", "user:password@host/dbname?charset=utf8&parseTime=True"] # mysql
# path = ["postgres", "host=host user=username dbname=pocketnpm sslmode=disable password=mypassword"]

# max in-memory cache size in MB (0 = unlimited)
max_cache_size = 2048
# in-memory cache eviction time in minutes
cache_lifetime = 1440

[mirror]
registry = "https://replicate.npmjs.com/registry"
concurrency = 20
path = "./registry/"
# interval for updates
interval = 120

[server]
bind = "0.0.0.0"
port = 80
# scheme and host to make tarball urls (host of registry.npmjs.org/package/-/package-version.tgz)
scheme = "http"
host = "localhost"
# send X-Accel-Redirect header to clients such as nginx and apache.
# see: https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/
x_accel_redirect = false
logpath = "pocketnpm.access.log"
