[database]
path = "npm.db"

[mirror]
registry = "https://replicate.npmjs.com/registry"
concurrency = 20
path = "./registry/"
# interval for updates
interval = 120

[server]
bind = "0.0.0.0"
port = 80
# scheme and host to make tarball urls (host of registry.npmjs.org/package/-/package-version.tgz)
scheme = "http"
host = "localhost"
# send X-Accel-Redirect header to clients such as nginx and apache.
# see: https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/
x_accel_redirect = false
