[database]
path = "npm.db"

[mirror]
registry = "https://replicate.npmjs.com/registry"
concurrency = 10
path = "./registry/"
# interval for updates
interval = 120

[server]
host = "0.0.0.0"
port = 80

